
const ListCommand = {
    "ADD_ENTITY" : "ADD_ENTITY",
    "MOVE_ENTITY" : "MOVE_ENTITY",
    "MYQ_ROBOT_MOVE_FORWARD" : "MYQ_ROBOT_MOVE_FORWARD",
    "MYQ_ROBOT_MOVE_BACKWARD" : "MYQ_ROBOT_MOVE_BACKWARD",
    "MYQ_ROBOT_ROTATE_LEFT" :  "MYQ_ROBOT_ROTATE_LEFT",
    "MYQ_ROBOT_ROTATE_RIGHT" : "MYQ_ROBOT_ROTATE_RIGHT",
    "MYQ_ROBOT_CLEANING" : "MYQ_ROBOT_CLEANING",
    "LOG_PUBLISH" : "LOG_PUBLISH"
}

export default ListCommand;
